CREATE OR REPLACE TRIGGER SYSTEM.TRG_INSERTINTOCUSTOMERS
  AFTER INSERT ON CUSTOMERS
  FOR EACH ROW
BEGIN
  INSERT INTO logs
  VALUES
    (LOG_SEQ.nextval,
     USER,
     'INSERT',
     SYSDATE,
     'CUSTOMERS',
     :new.cid);
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

