CREATE OR REPLACE TRIGGER SYSTEM.TRG_UPDATELASTVISIT
  AFTER UPDATE OF LAST_VISIT_DATE ON CUSTOMERS
  FOR EACH ROW
BEGIN
  INSERT INTO logs
  VALUES
    (LOG_SEQ.nextval,
     USER,
     'UPDATE',
     SYSDATE,
     'CUSTOMERS',
     :old.cid);

EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

